### ISSUE TITLE
make revealjs issue

### ISSUE THREAD

**Issue by rdauria** [attakei/sphinx-revealjs#28]
I have just installed sphinx reveal on my macOS Catalina (10.15.4) after updating python to 2.7.18, I can use sphinx w/ no problems with "make html" on a different  project, however when running `make  revealjs` on  a brand new project  (on which I have just run: `sphinx-quickstart`, imported index.rst from https://raw.githubusercontent.com/attakei/sphinx-revealjs/master/demo/index.rst and set the extensions to include `'sphinx_revealjs',`) I get:

```make revealjs
Running Sphinx v1.8.5

Exception occurred:
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx_revealjs/__init__.py", line 21
    def setup(app: Sphinx):
                 ^
SyntaxError: invalid syntax
The full traceback has been saved in /var/folders/pl/92c65mj12h160c67rs104hvh0000gn/T/sphinx-err-OXiwNr.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [revealjs] Error 2
```

and:

```cat /var/folders/pl/92c65mj12h160c67rs104hvh0000gn/T/sphinx-err-OXiwNr.log
# Sphinx version: 1.8.5
# Python version: 2.7.18 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sphinx_revealjs/__init__.py", line 21
    def setup(app: Sphinx):
                 ^
SyntaxError: invalid syntax
```

What  am I missing?

**Comment by attakei** [comment]
`sphinx-revealjs` is implemented to work on only python more than version 3.6.
This does not work on python 2.x
