### ISSUE TITLE
Some tests are not executed due to duplicate test method names

### ISSUE THREAD

**Issue by ftnext** [attakei/sphinx-revealjs#42]
## Environment

macOS
Python 3.9.0

- sphinx-revealjs 53029e1

## Problem

For example,

### tests/test_conf.py

```python
@with_app(**gen_app_conf(confoverrides={"revealjs_style_theme": "moon"}))
def test_revealjs_style_theme(self, app: TestApp, status, warning):
    ...

@with_app(**gen_app_conf(confoverrides={"revealjs_style_theme": "custom.css"}))
def test_revealjs_style_theme(self, app: TestApp, status, warning):
    ...
```

## Procedure

In running the nosetests task in VSCode, all tests pass.

```
> Executing task: poetry run nosetests tests/ <

...........................
----------------------------------------------------------------------
Ran 27 tests in 5.557s

OK
```

But if you change the name of the first test method, it fails. 

```python
@with_app(**gen_app_conf(confoverrides={"revealjs_style_theme": "moon"}))
def test_revealjs_style_theme_case1(self, app: TestApp, status, warning):  # rename
    ...

@with_app(**gen_app_conf(confoverrides={"revealjs_style_theme": "custom.css"}))
def test_revealjs_style_theme(self, app: TestApp, status, warning):
    ...
```

```
> Executing task: poetry run nosetests tests/ <

........F...................
======================================================================
FAIL: test_revealjs_style_theme_case1 (test_conf.BuildHtmlTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/.../venv/lib/python3.9/site-packages/sphinx_testing/util.py", line 171, in decorator
    return func(*(args + (app, status, warning)), **kwargs)
  File "/.../tests/test_conf.py", line 116, in test_revealjs_style_theme_case1
    self.assertEqual(len(links), 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 28 tests in 5.639s

FAILED (failures=1)
```

The number of tests executed has also increased by one.

## Problem summary

1. Some tests are not being executed. (Other tests may not be executed either for duplicate test method names)
2. At least `test_revealjs_style_theme` needs to be fixed.

**Comment by attakei** [comment]
Thanks for feedback! I have fix it on #54 .

I could not recognize it after mistake implement tests first...
